# Generated by Django 4.1.4 on 2023-02-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=300)),
                ('favorite', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Band',
        ),
    ]
