# Generated by Django 4.1.7 on 2023-03-29 09:55

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Femelle')], max_length=1)),
                ('age', models.IntegerField(validators=[animals.models.Animals.positive_age_validator])),
                ('taille', models.FloatField(validators=[animals.models.Animals.positive_taille_validator])),
            ],
        ),
    ]
